### ISSUE TITLE
Add to npm registry

### ISSUE THREAD

**Issue by tuckerconnelly** [wbotelhos/raty#152]
Would be nice for using with browserify

**Comment by rizumu** [comment]
+1

**Comment by polyn0m** [comment]
+1

**Comment by llaski** [comment]
+1

**Comment by wbotelhos** [comment]
Ok, but we do not have the namespace `raty` anymore `https://www.npmjs.com/package/raty`.

`ratyjs`?

**Comment by llaski** [comment]
`ratyjs` looks good to me.

**Comment by wbotelhos** [comment]
@llaski I follow the common names found there, check it out: https://www.npmjs.com/package/raty-js
