### ISSUE TITLE
Add Multiple Raty on Single Page

### ISSUE THREAD

**Issue by rajlaksh** [wbotelhos/raty#158]
How to Add Multiple Raty on Single Page?

**Here is code i'm using**

$(document).ready(function(){
$('#rating').raty({half:true,size:24,starHalf:'star-half.png',
starOff:'star-off.png',
starOn:'star-on.png',
path:img_url,start:$('#rating').attr('rel'),click:function(b,c){
var id = $(this).attr("#product_id");
$.post('ajax-rate.php',{'rating':b,'id':id},function(a){
if(a)alert("Thanks for your voting.");else alert("Sorry, something wrong with our server, please try it again later.")},"json")}});
});

**Edit: It show 1 rating only  when i added it 1 page whose has multiple rating**

**Comment by troyharvey** [comment]
You'll need to use a class selector. For example, try `.raty` instead of `#rating`

```
<div class="raty"></div>
<div class="raty"></div>

$(document).ready(function() {
    $('.raty').raty({
        half: true,
        size: 24,
        starHalf: 'star-half.png',
        starOff: 'star-off.png',
        starOn: 'star-on.png',
        path: img_url,
        click: function(b, c) {
            var id = $(this).attr("#product_id");
            $.post('ajax-rate.php', {
                'rating': b,
                'id': id
            }, function(a) {
                if (a) alert("Thanks for your voting.");
                else alert("Sorry, something wrong with our server, please try it again later.")
            }, "json")
        }
    });
});
```
