### ISSUE TITLE
how to use it with qtip 2?

### ISSUE THREAD

**Issue by rajlaksh** [wbotelhos/raty#172]
how to use it with qtip 2?

$('.qtip-titlebar span#rating').raty({ path: img_url,readOnly: true, score: $(this).data('rate')});
but it show 0 Stars where rating has 5 :(

That comes from Ajax.

**Comment by akatche** [comment]
Hi, im having the same issue. 
If someone could give a hint that would be great!
Thanks!

**Comment by rajlaksh** [comment]
I got it Somehow Working

$('.qtip-titlebar span#rating').raty({
half:true,size:5,starHalf:'star-half.png', starOff:'star-off.png', starOn:'star-on.png', path: img_url,start:$('#rating').attr('rel'),readOnly: true});

**Comment by akatche** [comment]
Hi @rajlaksh 
If you can could you show me the html that you put inside qtip2. Because i tried what you did but i cannot adapt it to what i made.

Thanks!

**Comment by rajlaksh** [comment]
$('.qtip-titlebar').html('<div class="title pull-left">'+data.title+'</div> <span class="pull-right" id="rating" rate="'+ data.rating +'"></span>');

**Comment by rajlaksh** [comment]
`$('.qtip-titlebar').html('<div class="title pull-left">'+data.title+'</div> <span class="pull-right" id="rating" rate="'+ data.rating +'"></span>');`
