### ISSUE TITLE
Feature to programatically update the score

### ISSUE THREAD

**Issue by basco-johnkevin** [wbotelhos/raty#180]
To set the score initially we can do:

```
$('div').raty({
  score: function() {
    return $(this).attr('data-score');
  }
});
```

But how can we update the score later? I've read the docs and also searched on Google but I can't find a way to programatically update the score.

**Comment by wbotelhos** [comment]
```js
$('div').raty('score', number);          // Set the score.
```

**Comment by basco-johnkevin** [comment]
@wbotelhos Ohhhh, its in the docs >.< I overlooked it yesterday, really sorry! Thank you!
