### ISSUE TITLE
Score to match star rating selected

### ISSUE THREAD

**Issue by stack-its** [wbotelhos/raty#183]
I'd like to record the rating in 1/2 star increments, instead of a float number.
Ex. Users see 2-1/2 stars showing (they expect rating of 2.5 on click) but score may be 2.76201....
I.e., it's not the score that they clicked. Is there a way to get the rating in 1/2 star increments ?

**Comment by mateuspv** [comment]
Hi @stack-its do you found a solution for this? I have the same problem...

**Comment by stack-its** [comment]
Hi @mateuspv
No, unfortunately not.  It's a basic function that I wish Washington would fix.
