### ISSUE TITLE
downloadable font: OS/2: bad linegap: -32

### ISSUE THREAD

**Issue by Henry-Cullen** [wbotelhos/raty#184]
I'm getting this error from the .woff font file of the raty font.
Any ideas why?

Firefox Dev tools OSX

**Comment by wbotelhos** [comment]
I've never seen, maybe someone can help you.

**Comment by wbotelhos** [comment]
I'll close this issue @Henry-Cullen , if someone else have this error, maybe we can try to find a bug on code.
