### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by MrOutis** [wbotelhos/raty#186]
Is there a way to prevent a user running this in their console?
```
$('div').raty({
  their: options
)};
```
the user can turn ```readOnly: false```

**Comment by wbotelhos** [comment]
Console is always open for that.
Facebook prevents Firebug in some way, but I have no ideia about it.

**Comment by MrOutis** [comment]
Thanks for the Facebook reference, I found this.
https://davidwalsh.name/disable-console

**Comment by markvantilburg** [comment]
A server side check is the way to go, what if they use http://www.telerik.com/fiddler or another proxy to change the value?
