### ISSUE TITLE
Update star rating only on success after click

### ISSUE THREAD

**Issue by saadtambe** [wbotelhos/raty#194]
Hello,

I am trying to achieve something like:

('div').raty({
            click: function(score, event){
              if(success on some conditiions){
                      ............     
                    //update rating stars
               } else {
                    ............... 
                  // do not update rating stars
                  }
            }
})

However irrespective of the success condition the stars are updated to the clicked rating value. Please help !

Thanks in advance.

**Comment by wbotelhos** [comment]
Hi,

You need to `return false` to prevent it.

**Comment by saadtambe** [comment]
Thanks a ton ! It worked :+1:
