### ISSUE TITLE
How to set the  stars to a different value in the click function

### ISSUE THREAD

**Issue by saadtambe** [wbotelhos/raty#195]
Hello, 

Suppose a user has clicked on 5 star, I want to do the following

('div').raty({
click: function(score, event){

............
//Set score to 4 star and have 4 star(Not 5 Star) selection reflected on UI 
}
)

Thanks in advance.

**Comment by wbotelhos** [comment]
Hi,

Please, check the documentation:

```
$('div').raty('score', number);          // Set the score.
```

**Comment by saadtambe** [comment]
Thank you for the response.

 I tried using $('div').raty('score', 4) in the click function;

However the selection is set to 5 star on the UI after clicking 5 star.

Please help !. Thanks.

**Comment by wbotelhos** [comment]
Did you prevent the score with `return false`?

**Comment by saadtambe** [comment]
Sorry, didn't quite get that.

Please see below is the code snippet: 

('div').raty({
click: function(score, event){
   if(success on some conditiions){
      ............
       if (score == 5) {
        $('div').raty('score', 4)
      }
  } else {
             ...............
             return false;
    }
}
})

**Comment by wbotelhos** [comment]
You return is on `else`, but you action is on `if`.

**Comment by saadtambe** [comment]
Ahh, I was missing the return.  Thanks so much !!
