### ISSUE TITLE
Browsing back to page with stars doubles the stars

### ISSUE THREAD

**Issue by arta** [wbotelhos/raty#198]
When I return to page containing raty star ratings via browser's Back button, the number of stars is doubled (although the extra set is not responsive to mouseover).

![screen shot 2016-12-26 at 9 09 41 pm](https://cloud.githubusercontent.com/assets/129580/21489386/b6b48786-cbaf-11e6-9ff6-d1d38f5fb31c.png)

**Comment by jakeland** [comment]
Hey, in case you need a quick fix, I've found that by adding : 
`   $('.star-rating').raty('reload');`
before the function that renders the stars, you can avoid this problem. 

To clarify, this is the way my code is set up
```
//reload stars/stop duplication
$('.star-rating').raty('reload');
//get rating
  $('.star-rating').raty({
    path: '/assets/',
    readOnly:true,
    score: function(){
      return($(this).attr('data-score'));
    }
  })
```
