### ISSUE TITLE
node ^8 Requirement

### ISSUE THREAD

**Issue by ecabuk** [wbotelhos/raty#210]
Is node 8 a strict requirement? Because I cannot use it on node v9 with yarn. It says:

```
error raty-js@2.8.0: The engine "node" is incompatible with this module. Expected version "^8".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

There is a workaround but it's annoying:

```
yarn --ignore-engines upgrade
```

https://github.com/wbotelhos/raty/blob/b4282b9a230c6da0973e7b3590d831e893a98954/package.json#L32

**Comment by wbotelhos** [comment]
Hi @ecabuk ,

It is not. Could you open a pull request removing it?

**Comment by hoangnkvti** [comment]
I'm using node 8.12.0 but can not install

**Comment by wbotelhos** [comment]
Hi @hoangnkvti , removes the `node` entry solves the problem?
