### ISSUE TITLE
Raty not working on Rails 6

### ISSUE THREAD

**Issue by jinshiq** [wbotelhos/raty#228]
When I used raty to my Rails 6 application, it caused an error "_Uncaught TypeError: $(...).raty is not a function_" in Chrome developers console.

The steps that I followed are described below.

1. copy https://github.com/wbotelhos/raty/tree/master/lib/jquery.raty.js to 
    /app/javascript/ of my application.

2. copy https://github.com/wbotelhos/raty/tree/master/lib/jquery.raty.css to
   /app/assets/stylesheets/ of my application.

3. copy all images in https://github.com/wbotelhos/raty/tree/master/lib/images to
   /app/assets/stylesheets/images/ of my application.

4. use _'yarn add jquery_' to install jquery. (I have confirmed jquery is working without any issue.)

5. The /config/webpack/environment is configured as below.

      const { environment } = require('@rails/webpacker')
      const webpack = require('webpack')
      environment.plugins.prepend('Provide',
        new webpack.ProvidePlugin({
            $: 'jquery/src/jquery',
              jQuery: 'jquery/src/jquery'
           })
       )
      module.exports = environment

6. The /app/javascript/webpack/application.js is configured as below.

      require("@rails/ujs").start()
      require("turbolinks").start()
      require("@rails/activestorage").start()
      require("channels")
      require("jquery")
      require("jquery.raty")

7. add below code to application.html.erb.
   `<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>`

7. add below raty code to my show.html.erb.
`<div class="rating" id="star"></div>`
`<script> $('#star').raty({score: 3});<script>`

8. After I ran my application, the raty was not working at all. No images (stars) were showed. Nothing about raty was displayed in the View show.html.erb.

9. When I opened the Inspect console in Chrome browser, I saw below error message.
     Uncaught TypeError: $(...).raty is not a function

    Seems jquery.raty was not successfully integrated to Rails 6 javacript compiling. But I don't know why this happens and how to solve it.  

10. I also tried to run '_yarn add raty-js_' and add require("raty-js") to application.js. But it had the same issue.

**Comment by wrmk** [comment]
https://linuxtut.com/en/eb6848c6025ca63af1c4/ 
works fine

**Comment by wbotelhos** [comment]
Thanks for that article, @wrmk . I'm not using Raty inside the Webpacker yet, so I can't point the problem, but the article should explain it better. I'll save it for my upgrade, thanks!

**Comment by eliasglyptis** [comment]
Maybe jQuery isn't available in your views?
If so perhaps try in application.js

global.$ = require("jquery")

**Comment by wbotelhos** [comment]
@eliasglyptis Thanks for your answer!

Since Raty has dropped the jQuery dependency, I recommend @jinshiq upgrade it.
