### ISSUE TITLE
How to create stars at runtime

### ISSUE THREAD

**Issue by ptahchiev** [wbotelhos/raty#229]
Hello,
I have the following problem. I am calling an API with AJAX on the server and the response contains a field `rating` and I need to create stars at runtime based on that field. How can I achieve this? How can I create the HTML elements to append them them to the dom tree?

**Comment by wbotelhos** [comment]
Hi, @ptahchiev .

Would be nice if you already have the HTML and just execute the Raty inside your Ajax callback. Something like:

```js
success: function() {
  $('#my-tag').raty();
}
```

But if you don't have the wrapper, you need to create it first:

```js
  $('<div />', { id: 'my-tag' }).appendTo('body').raty();
```

**Comment by ptahchiev** [comment]
This is what i ended up with:
```
function createRatingHtml(rating) {
    let result = $("<div class='rating mt-3' data-rating='" + rating + "'></div>").append($("<div class='rating mt-3' data-rating='" + rating + "'></div>").raty
    ({
                    starType: 'i',
                    half: true,
                    scoreName: 'rating',
                    score: rating ? rating : 0,
                    readOnly: true,
                    width: 200
                }))[0];

    return result.outerHTML || new XMLSerializer().serializeToString(result);
}
```
