### ISSUE TITLE
Removes Karma and Jasmine In Favor of Jest

### ISSUE THREAD

**Issue by wbotelhos** [wbotelhos/raty#237]
We should drop Jasmine and jQuery from the tests. I suggest the [JestJS](https://jestjs.io), but it can be any modern library.

**Comment by anudeeps0306** [comment]
Can you please assign this to me?

**Comment by baterson** [comment]
Hey! I can also help with tests rewrite

**Comment by wbotelhos** [comment]
Nice, @baterson ! I’m merging the ES6 conversion today. After that, you’re good to go.

**Comment by wbotelhos** [comment]
Hey, @baterson . We're good to go. Could you add your plan here? Will we migrate it to Jest and remove totally the jQuery?

**Comment by bukhtiyarov-a-v** [comment]
Hi, @wbotelhos! I can take the task, my plan is pretty simple now: 
1) Introduce Jest, configure test environment 
2) Rewrite all cases that are currently in repo.

**Comment by baterson** [comment]
@bukhtiyarov-a-v Hey! I think you can go for it since no one started it. I'm limited in time right now unfortunately, but I can jump in to help with the test suites when everything is set up and ready.

**Comment by wbotelhos** [comment]
Hi, @bukhtiyarov-a-v , go ahead!

I think we don't need to drop Karma since it makes it easy to run different browsers. I did a quick search and the options look to be much more complex. But, I'm not a JS expert and for sure I'm outdated.

Could we start like this?:

1. Replace Jasmine with Jest;
2. Drop jQuery;
3. Review if Karma should be replaced.

**Comment by bukhtiyarov-a-v** [comment]
@wbotelhos, actually, with Jest we don't need an in-browser test runner. We have JSDOM environment we can run all tests in, it's W3C compliant. Also, I've never seen anyone using Jest with Karma, so maybe it's not worth trying to make them friends. I already removed Karma, together with introducing Jest, and it seems to run smooth by far.

**Comment by wbotelhos** [comment]
close by https://github.com/wbotelhos/raty/pull/242

**Comment by bukhtiyarov-a-v** [comment]
@wbotelhos looks like you can close this issue. Or is there something left to be done here?
