### ISSUE TITLE
JQuery defer or reduced javascript?

### ISSUE THREAD

**Issue by eezis** [wbotelhos/raty#248]
The jquery dependency is painful when it comes to lighthouse and other performance scores. Has anyone stripped out the unused javascript to create a smaller file? Or has anyone used the defer option to load raty and jquery? If I defer the packages the stars don't show up on the html page. 

Are there any tricks that folks are using to get faster load times?

**Comment by wbotelhos** [comment]
I'm closing it because we no more depends on jQuery.
