### ISSUE TITLE
No effect

### ISSUE THREAD

**Issue by ajiho** [wbotelhos/raty#252]
`<script src="../lib/raty-js/build/raty.min.js"></script>`

` <div id="raty"></div>`

```
        new Raty(document.querySelector('#raty'), {
            starType: 'i',
        });
```

The browser is blank, please tell me how to do it?

**Comment by tuchuan-cai** [comment]
You should call the `init` method. like this:
```
const raty = new Raty(document.querySelector('#raty'), {
    starType: 'i',
});
raty.init();
```
and copy these photos to here:
![image](https://github.com/wbotelhos/raty/assets/52688680/3168d48a-feee-4b9a-90e8-7a7def15d1dd)

**Comment by wbotelhos** [comment]
Thank you, @tuchuan-cai .

**Comment by ajiho** [comment]
@tuchuan-cai think you,As you said, it works
