### ISSUE TITLE
Build breaks the score calculation in half

### ISSUE THREAD

**Issue by markvantilburg** [wbotelhos/raty#254]
This line in source is different in the build version:
https://github.com/wbotelhos/raty/blob/ab208034b0d173a3b2404b51f487ab577a21f969/src/raty.js#L560

The file in build looks like this:
const percent = parseFloat((evt.pageX - icon.offsetLeft) / size);

@wbotelhos why is this different? The changed calculation breaks the rendering of the stars in my page. Either the file in the build folder is not up to date or the compiler broke this line.

On my page:
getBoundingClientRect: 877.2999877929688
offsetLeft :204

This huge difference makes that the offsetLeft version marks all stars instead of the correct one.

**Comment by markvantilburg** [comment]
Looking at #249 the file in the build folder is outdated (in the release zipfile and this repo).

**Comment by wbotelhos** [comment]
Hi @markvantilburg ,

I didn't run the build before the release. It was fixed at [v4.3.0](https://github.com/wbotelhos/raty/releases/tag/v4.3.0). Thanks!
