### ISSUE TITLE
Assigning .raty() to a class for use with multiple displays of rating stars for different 'objects' on a single page

### ISSUE THREAD

**Issue by jessemarple** [wbotelhos/raty#3]
For a project, I'm wanting to use .raty to show the rating set by a member for particluar object (event, restaurant, etc).  I have four different methods: getReviewsByNameAscending, getReviewsByNameDescending, etc . . . 

However, it seems as though I can only get raty to work correctly when I'm working with a SINGLE dom element (e.g. an ID or a CLASS that doesn't any siblings in the same class).  What occurs when I use a class (and am applying .raty during an $each loop), is that all of the values for the for the rating are displayed (so, if there are four reviews, then you see four sets of stars for each review when there should (ideally) be only the set of stars related to that particular review.

Thoughts or ideas? 

 .raty is the CLEANEST solution out there for jquery rating.  Period.  Anyone reading this shouldn't be dissuaded by my issues from using it.  I am trying to do something I dont think .raty was build for or can handle without some augmentation.  Again, if you're looking for a easy, flexible jquery rating solution, .raty is it.

**Comment by shabari585** [comment]
when i am using raty-js in angular4 in ngFor loop it is not functioning .please help me:(
