### ISSUE TITLE
Can't load raty on divs generated by a $.ajax function

### ISSUE THREAD

**Issue by Patatouf** [wbotelhos/raty#64]
Hi,

I am using a $.ajax function to add new "comments" including raty divs on my page . But I can't apply the plugins on these new divs. Even if I run a "setRaty" function that executes something like $('.raty').raty({...}); the stars don't appear. Although, if I do $('.raty').html('test'); this runs correctly.
NB : the raty plugin works well with existing divs when the page is loaded.

Thank you for your help !

Jeremy

**Comment by arnabrahman** [comment]
I'm facing same problem. Can you show some code?

**Comment by wbotelhos** [comment]
Since raty already imported, it is ok.
