### ISSUE TITLE
Change color range

### ISSUE THREAD

**Issue by michaelthuren** [wbotelhos/raty#71]
Raty is the best star rating plugin imo.

The only thing i'm missing is to switch the starOn images on stars less then the hovered

like this: http://www.htmldrive.net/items/show/170/Colourful-rating-system-with-CSS3-And-jQuery

[1] [0] [0] [0] [0]
[2] [2] [0] [0] [0]
[3] [3] [3] [0] [0]
[4] [4] [4] [4] [0]
[5] [5] [5] [5] [5]

**Comment by wbotelhos** [comment]
Solved by https://github.com/wbotelhos/raty/issues/135
