### ISSUE TITLE
How can I save the rating?

### ISSUE THREAD

**Issue by sandino** [wbotelhos/raty#91]
Is raty supposed to be saved?

**Comment by candidexmedia** [comment]
> @wbotelhos : sorry for my dumb question, but how can I save the score to my database?. I use php zend framework and doctrine ORM

I'm curious about this as well.

**Comment by wbotelhos** [comment]
Hi, @candidexmedia .

How to save the value depends on you framework. Raty is just a plugin that populates a hidden field. This field should be inside a form and when you submit the form, the value will be submitted to your controller-ish. Then how you'll save the value depends of your framework. Se an example with [Rails](https://www.javatpoint.com/ruby-on-rails-save-record).

Save a value to the database is other context, the plugin just transform a click into a number.
